<?php

/**
 * @file
 * Contains quizzer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function quizzer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the quizzer module.
    case 'help.page.quizzer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create quizzes and tests') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function quizzer_theme() {
  return [
    'quizzer' => [
      'render element' => 'children',
    ],
  ];
}
